name: flash_chat
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.2.0"

dependencies:
  flutter:
    sdk: flutter
  
  firebase_auth: ^0.15.5+3
  google_sign_in: ^4.4.1
  provider: ^3.1.0
  google_maps_flutter: ^0.5.25+3
  location: ^3.0.0
  google_map_polyline: ^0.2.0+1
  flutter_polyline_points: ^0.1.0
  permission: ^0.1.7
  firebase_database: ^3.1.3



  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
  - images/
